apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
